InventoryManager/Models/History.cs
using System;
using System.Data.Entity.ModelConfiguration;

namespace InventoryManager.Models
{
    public class History
    {
        public int Id { get; set; }

        public int InventoryId { get; set; }
        public Inventory Inventory { get; set; }

        public DateTime AssignedOn { get; set; }

        public string AssignedById { get; set; }
        public ApplicationUser AssignedBy { get; set; }

        public int AssignedToId { get; set; }
        public Owner AssignedTo { get; set; }

        public InventoryStatus StatusAssigned { get; set; }

    }
}

InventoryManager/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventoryManager.Models;
using InventoryManager.ViewModel;
using PagedList;

namespace InventoryManager.Controllers
{
    [Authorize(Roles = "InventoryCustomerManager, InventoryManager, InventoryAdmin")]
    public class HistoryController : Controller
    {
        private InventoryContext db = new InventoryContext();
        // GET: HardwareType
        public ActionResult Index(int? Id, HistoryList viewModel)
        {
            if(Id == null) return new HttpNotFoundResult();

            var inventory = db.Inventories
                .Include(i => i.Owner)
                .SingleOrDefault(i => i.Id == Id);

            if(inventory == null) return new HttpNotFoundResult();
            viewModel.Inventory = inventory;

            viewModel.Histories = db.Histories
                .Include(i => i.AssignedBy)
                .Include(i => i.AssignedTo)
                .Where(i => i.InventoryId == Id)
                .OrderByDescending(i => i.AssignedOn)
                .ToPagedList(viewModel.Page, viewModel.PageSize);

            return View(viewModel);
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

InventoryManager/Views/History/Index.cshtml
@using PagedList.Mvc
@model InventoryManager.ViewModel.HistoryList
@{
    ViewBag.Title = Model.Inventory.Name;

    Layout = "../Shared/_FormLayout.cshtml";
}

@section PageHead{
    <h2>History: @ViewBag.Title <span class="label label-@Model.Inventory.Status">@Model.Inventory.Status</span></h2>
    <div class="info">
        <span class="info-type"><i class="fa fa-user"></i> Owner:</span>
        @Model.Inventory.Owner.Name
    </div>
}

@section MenuControls {
    <ul>
        <li>
            
        </li>
    </ul>
}

<div class="list">
    @if (Model.Histories.Count > 0)
    {
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th width="25%">Assigned By</th>
                <th class="col-sm-2 text-center">Assigned To</th>
                <th class="col-sm-2 text-center">Status</th>
                <th class="col-sm-1 text-right">Assigned Date</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var history in Model.Histories)
            {
                <tr>
                    <td>
                        <a href="#">@history.AssignedBy.UserName</a>
                    <td class="text-center">
                        <a href="#">@history.AssignedTo.Name</a>
                    </td>
                    <td class="text-center">
                        <span class="label label-@history.StatusAssigned">@history.StatusAssigned</span>
                    </td>

                    <td class="text-right">@history.AssignedOn</td>
                </tr>
            }
            </tbody>
        </table>

        if (Model.Histories.PageSize < Model.Histories.TotalItemCount)
         {
             <div class="text-center">
                 @Html.PagedListPager(Model.Histories, page => Url.Action("Index", "History",
                     new {Id = Model.Inventory.Id, page}))
             </div>
         }
    }
    else
    {
        <div class="text-center">
            No History for @Model.Inventory.Name
        </div>
    }
</div>