InventoryManager/Controllers/ContactController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using InventoryManager.Models;
using InventoryManager.ViewModel;

namespace InventoryManager.Controllers
{
    [Authorize(Roles = "InventoryCustomerManager, InventoryAdmin")]
    public class ContactController : Controller
    {
        private InventoryContext db = new InventoryContext();

        public ActionResult Add(int CustomerId = 0)
        {
            if (CustomerId == 0) return new HttpNotFoundResult();

            if (!db.Customers.Any(c => c.Id == CustomerId)) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var contact = new ContactData();
            contact.CustomerId = CustomerId;

            return View(contact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ContactData c)
        {
            if(c.CustomerId == 0) return new HttpNotFoundResult();

            if(!ModelState.IsValid) return View(c);
            
            var contact = new Contact();
            db.Contacts.Add(contact);

            MapContact(contact, c);
            db.SaveChanges();

            TempData["AlertMessage"] = "Contact Saved";
            return RedirectToAction("Show", "Customer", new { Id = c.CustomerId });
        }

        public ActionResult Edit(int? Id)
        {
            if (Id == null) return new HttpNotFoundResult();

            var contact = db.Contacts.SingleOrDefault(l => l.Id == Id);
            if (contact == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var viewModel = new ContactData();
            PopulateContactData(contact, viewModel);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContactData c)
        {
            if (c.CustomerId == 0) return new HttpNotFoundResult();

            if (!ModelState.IsValid) return View(c);

            var contact = db.Contacts.SingleOrDefault(i => i.Id == c.Id);
            if (contact == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            MapContact(contact, c);
            db.SaveChanges();

            TempData["AlertMessage"] = "Contact Saved";
            return RedirectToAction("Show", "Customer", new { Id = c.CustomerId });
        }

        public void MapContact(Contact contactToUpdate, ContactData data)
        {
            contactToUpdate.CustomerId = data.CustomerId;
            contactToUpdate.FirstName = data.FirstName;
            contactToUpdate.LastName = data.LastName;
            contactToUpdate.Phone = data.Phone;
            contactToUpdate.Email = data.Email;

        }

        public void PopulateContactData(Contact contact, ContactData contactToDisplay)
        { 
            contactToDisplay.CustomerId = contact.CustomerId;
            contactToDisplay.FirstName = contact.FirstName;
            contactToDisplay.LastName = contact.LastName;
            contactToDisplay.Phone = contact.Phone;
            contactToDisplay.Email = contact.Email;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

InventoryManager/Controllers/CustomerController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using InventoryManager.Models;
using InventoryManager.ViewModel;
using PagedList;

namespace InventoryManager.Controllers
{
    [Authorize(Roles = "InventoryCustomerManager, InventoryAdmin")]
    public class CustomerController : Controller
    {
        private InventoryContext db = new InventoryContext();

        // GET: Owner
        public ActionResult Index(CustomerListView viewModel)
        {
            viewModel.CustomerLists = db.Customers
                .Select(c => new CustomerList()
                {
                    Customer = c,
                    Owner = c.Owner,
                    Count = c.Owner.Inventories.Count
                })
                .OrderBy(c => c.Owner.Name)
                .ToPagedList(viewModel.Page, viewModel.PageSize);

            return View(viewModel);
        }

        public ActionResult Add()
        {
            var viewModel = new CustomerData();
            
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CustomerData c)
        {
            if (!ModelState.IsValid) return View(c);

            var customer = new Customer();
            var owner = new Owner();

            customer.Owner = owner;
            customer.Owner.OwnerType = OwnerType.Customer;

            MapCustomer(customer, c);
            customer.Owner.CreatedOn = DateTime.Now.Date;

            db.Customers.Add(customer);
            db.SaveChanges();

            TempData["AlertMessage"] = "Customer Saved";
            return RedirectToAction("Show", "Customer", new { customer.Id });
        }

        private void MapCustomer(Customer customerToUpdate, CustomerData data)
        {
            customerToUpdate.Owner.Name = data.Name;
            customerToUpdate.Description = data.Description;
            customerToUpdate.Owner.ModifiedOn = DateTime.Now.Date;
        }

        private void PopulateCustomer(Customer customer, CustomerData customerToDisplay)
        {
            customerToDisplay.Name = customer.Owner.Name;
            customerToDisplay.Description = customer.Description;
            customerToDisplay.Id = customer.Id;
        }

        public ActionResult Edit(int? Id)
        {
            if(Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var customer = db.Customers
                .Include(c => c.Owner)
                .SingleOrDefault(c => c.Id == Id);

            if (customer == null) return new HttpNotFoundResult();

            var viewModel = new CustomerData();
            PopulateCustomer(customer, viewModel);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomerData c)
        {
            if (c.Id == 0) return new HttpNotFoundResult();

            var customer = db.Customers
                .Include(i => i.Owner)
                .SingleOrDefault(i => i.Id == c.Id);

            if (customer == null) return new HttpNotFoundResult();

            MapCustomer(customer, c);

            db.SaveChanges();

            TempData["AlertMessage"] = "Customer Saved";
            return RedirectToAction("Show", "Customer", new { customer.Id });
        }

        public ActionResult Show(int? Id)
        {
            if (Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var viewModel = new CustomerData();

            var customer = db.Customers
                .Include(c => c.Owner)
                .Include(c => c.Locations)
                .Include(c => c.Contacts)
                .SingleOrDefault(c => c.Id == Id);

            if (customer == null) return new HttpNotFoundResult();

            PopulateCustomer(customer, viewModel);

            viewModel.Locations = customer.Locations;
            viewModel.Contacts = customer.Contacts;

            return View(viewModel);
        }

        public ActionResult ListInventories(int? Id, CustomerHardwareView viewModel)
        {
            if (Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var customer = db.Customers
                .Include(i => i.Owner)
                .SingleOrDefault(c => c.Id == Id);

            if (customer == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            viewModel.Customer = customer;

            viewModel.Inventories = db.Inventories
                .Where(i => i.Owner.Id == customer.Owner.Id)
                .OrderBy(i => i.Name)
                .ToPagedList(viewModel.Page, viewModel.PageSize);

            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

InventoryManager/Controllers/LocationController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using InventoryManager.Models;
using InventoryManager.ViewModel;

namespace InventoryManager.Controllers
{
    [Authorize(Roles = "InventoryCustomerManager, InventoryAdmin")]
    public class LocationController : Controller
    {
        private InventoryContext db = new InventoryContext();


        public ActionResult Add(int CustomerId = 0)
        {
            if (CustomerId == 0) return new HttpNotFoundResult();

            if (!db.Customers.Any(c => c.Id == CustomerId)) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var location = new LocationData();
            location.CustomerId = CustomerId;

            return View(location);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(LocationData c)
        {
            if (c.CustomerId == 0) return new HttpNotFoundResult();

            if (!ModelState.IsValid) return View(c);

            var location = new Location();
            db.Locations.Add(location);

            MapLocation(location, c);
            db.SaveChanges();

            TempData["AlertMessage"] = "Location Saved";
            return RedirectToAction("Show", "Customer", new { Id = c.CustomerId });
        }

        public ActionResult Edit(int? Id)
        {
            if (Id == null) return new HttpNotFoundResult();

            var location = db.Locations.SingleOrDefault(l => l.Id == Id);
            if (location == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var viewModel = new LocationData();
            PopulateLocationData(location, viewModel);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LocationData c)
        {
            if (c.CustomerId == 0) return new HttpNotFoundResult();

            if (!ModelState.IsValid) return View(c);

            var location = db.Locations.SingleOrDefault(i => i.Id == c.Id);
            if (location == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            MapLocation(location, c);
            db.SaveChanges();

            TempData["AlertMessage"] = "Location Saved";
            return RedirectToAction("Show", "Customer", new { Id = c.CustomerId });
        }

        public void MapLocation(Location locationToUpdate, LocationData data)
        {
            locationToUpdate.CustomerId = data.CustomerId;
            locationToUpdate.Street = data.Street;
            locationToUpdate.Unit = data.Unit;
            locationToUpdate.City = data.City;
            locationToUpdate.State = data.City;
            locationToUpdate.Zip = data.Zip;
            locationToUpdate.Phone = data.Phone;
            locationToUpdate.Fax = data.Fax;

        }

        public void PopulateLocationData(Location location, LocationData locationToDisplay)
        {
            locationToDisplay.CustomerId = location.CustomerId;
            locationToDisplay.Street = location.Street;
            locationToDisplay.Unit = location.Unit;
            locationToDisplay.City = location.City;
            locationToDisplay.State = location.City;
            locationToDisplay.Zip = location.Zip;
            locationToDisplay.Phone = location.Phone;
            locationToDisplay.Fax = location.Fax;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }

}

InventoryManager/Views/Customer/Add.cshtml
@model InventoryManager.ViewModel.CustomerData
@{
    ViewBag.Title = "Add Customer";
    ViewBag.Submit = "Add Customer";

    Layout = "../Shared/_FormLayout.cshtml";

}

@section PageHead{
    <h2>@ViewBag.Title</h2>
}

@section MenuControls {
    <a href="@Model.ReferrerUrl" class="btn btn-default">
        <i class="fa fa-undo"></i> Cancel
    </a>
    <button type="button" onclick="javascript: document.getElementById('form-add').submit();" class="btn btn-primary">
        <i class="fa fa-plus"></i> @ViewBag.Submit
    </button>
}

<div class="container-fluid">

    @using (Html.BeginForm("Add", "Customer", FormMethod.Post, htmlAttributes: new { @id = "form-add" }))
    {
        @Html.AntiForgeryToken()

        Html.RenderPartial("__form_add_customer");
    }

</div>

InventoryManager/Views/Customer/Edit.cshtml
@model InventoryManager.ViewModel.CustomerData
@{
    ViewBag.Title = "Edit Contact";
    ViewBag.Submit = "Save Contact";

    Layout = "../Shared/_FormLayout.cshtml";

}

@section PageHead{
    <h2>@ViewBag.Title</h2>
}

@section MenuControls {
    <a href="@Model.ReferrerUrl" class="btn btn-default">
        <i class="fa fa-undo"></i> Cancel
    </a>
    <button type="button" onclick="javascript: document.getElementById('form-edit').submit();" class="btn btn-primary">
        <i class="fa  fa-floppy-o"></i> @ViewBag.Submit
    </button>
}




<div class="container-fluid">

    @using (Html.BeginForm("Edit", "Customer", FormMethod.Post, htmlAttributes: new { @id = "form-edit" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(c => c.Id)

        Html.RenderPartial("__form_add_customer");
    }

</div>

InventoryManager/Views/Customer/Index.cshtml
@using PagedList.Mvc
@model InventoryManager.ViewModel.CustomerListView
@{
    ViewBag.Title = "Customers";
    Layout = "../Shared/_FormLayout.cshtml";
}

@section PageHead{
    <h2>@ViewBag.Title</h2>
}

@section MenuControls {
    <ul>
        <li>
            <a href="@Url.Action("Add", "Customer")"><i class="fa fa-plus"></i> Add Customer</a>
        </li>
    </ul>
}
<div class="list">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th class="col-sm-8">Name</th>
            <th class="col-sm-2">Inventory Count</th>
            <th class="col-sm-2 text-right">Action</th>
        </tr>
        </thead>

        @foreach (var customerList in Model.CustomerLists)
        {
            <tr class="">
                <td>@customerList.Customer.Owner.Name</td>
                <td><a href="@Url.Action("ListInventories", "Customer", new {Id = customerList.Customer.Id})">@customerList.Count</a></td>
                <td class="text-right">
                    <a href="@Url.Action("Show", "Customer", new {Id = customerList.Customer.Id})" class="mini-btn">
                        <i class="fa fa-eye"></i>
                    </a>
                    <a href="@Url.Action("Edit", "Customer", new {Id = customerList.Customer.Id})" class="mini-btn">
                        <i class="fa fa-pencil"></i>
                    </a>
                </td>
            </tr>
        }
    </table>
    
    @if (Model.CustomerLists.PageSize < Model.CustomerLists.TotalItemCount)
    {
        <div class="text-center">
            @Html.PagedListPager(Model.CustomerLists, page => Url.Action("Index",
                new {page}))
        </div>
    }
</div>

InventoryManager/Views/Customer/ListInventories.cshtml
@using PagedList.Mvc
@model InventoryManager.ViewModel.CustomerHardwareView
@{
    ViewBag.Title = Model.Customer.Owner.Name;

    Layout = "../Shared/_FormLayout.cshtml";
}

@section PageHead{
    <h2><a href="@Url.Action("Show", "Customer", new {Id = Model.Customer.Id})">
            @ViewBag.Title
        </a>
    </h2>
    <div class="info">
        <span class="info-type">Total Inventories: </span>
        @Model.Inventories.TotalItemCount
    </div>
}

@section MenuControls {
    <ul>
        <li>
            <a href="@Url.Action("Index", "Customer")"><i class="fa fa-undo"></i> Back to Customers</a>
        </li>
    </ul>
}

<div class="list">
    @if (Model.Inventories.Count > 0)
    {
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th class="col-sm-6">Name</th>
                <th class="col-sm-2 text-center">Status</th>
                <th class="col-sm-2">Created On</th>
                <th class="col-sm-1 text-right">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var inventory in Model.Inventories)
            {
                <tr>
                    <td>
                        <a href="#">
                            @inventory.Name
                        </a>
                    </td>
                    <td class="text-center">
                        <span class="label label-@inventory.Status">@inventory.Status</span>
                    </td>
                    <td>@inventory.CreatedOn</td>
                    <td class="text-right">
                        <a href="@Url.Action("Show", "Inventory", new {Id = @inventory.Id})" class="mini-btn">
                            <i class="fa fa-eye"></i>
                        </a>

                    </td>
                </tr>
            }
            </tbody>
        </table>
        if (Model.Inventories.PageSize < Model.Inventories.TotalItemCount)
         {
             <div class="text-center">
                 @Html.PagedListPager(Model.Inventories, page => Url.Action("ListInventories", "Customer",
                     new {Id = Model.Customer.Id, page}))
             </div>
         }
    }
    else
    {
        <div class="text-center">
            No Inventories Assigned to @Model.Customer.Owner.Name
        </div>
    }
</div>

InventoryManager/Views/Customer/Show.cshtml
@model InventoryManager.ViewModel.CustomerData
@{
    ViewBag.Title = Model.Name;

    Layout = "../Shared/_FormLayout.cshtml";
}


@section PageHead{
    <h2>@ViewBag.Title</h2>
}

@section MenuControls {
    <ul>
        <li>
            <a href="@Url.Action("ListInventories", "Customer", new {Id = Model.Id})">
                <i class="fa fa-list"></i> List Inventories
            </a>
        </li>
        <li>
            <a href="@Url.Action("Delete", "Customer", new {Id = Model.Id})">
                <i class="fa fa-trash"></i> Delete
            </a>
        </li>
        <li>
            <a href="@Url.Action("Edit", "Customer", new {Id = Model.Id})">
                <i class="fa fa-pencil"></i> Edit
            </a>
        </li>
    </ul>
}

@{Html.RenderPartial("_form_view");}

@{Html.RenderPartial("__form_locations"); }
    
@{Html.RenderPartial("__form_contact");}

InventoryManager/Views/Customer/__form_add_customer.cshtml
@model InventoryManager.ViewModel.CustomerData

@*Form Add Contact*@
<div class="row">
    @Html.LabelFor(c => c.Name, htmlAttributes: new {@class = "col-sm-2"})
    <div class="col-sm-10">
        <div class="form-group">
            @Html.TextBoxFor(c => c.Name, htmlAttributes: new {@class = "form-control"})
            @Html.ValidationMessageFor(c => c.Name, "", new {@class = "text-danger"})
        </div>
    </div>
</div>

<div class="row">
    @Html.LabelFor(c => c.Description, htmlAttributes: new {@class = "col-sm-2"})
    <div class="col-sm-10">
        <div class="form-group">
            @Html.TextAreaFor(c => c.Description, htmlAttributes: new {@class = "form-control"})
            @Html.ValidationMessageFor(c => c.Description, "", new {@class = "text-danger", @rows = "6"})
        </div>
    </div>
</div>

InventoryManager/Views/Customer/__form_contact.cshtml
@model InventoryManager.ViewModel.CustomerData
    

<div class="section">
    <div class="section-header">
        <h3>Customer Contact</h3>
        <div class="section-controls">
            <a href="@Url.Action("Add", "Contact", new { CustomerId = Model.Id})">
                <i class="fa fa-plus"></i> Add New
            </a>
        </div>
    </div>
    <div class="separator"></div>
</div>

<div class="list">
    @if (Model.Contacts.Count > 0) { 
        <table class="table table-striped table-hover">
            <thead class="">
            <tr>
                <th>Customer name</th>
                <th>Phone</th>
                <th>Email</th>
                <th class="text-right">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var contact in Model.Contacts)
            {
                <tr>
                    <td>
                        <a href="#">
                            <i class="fa fa-user"></i> @contact.FirstName @contact.LastName
                        </a>
                    </td>
                    <td>
                        @contact.Phone
                    </td>
                    <td><a href="mailto:@contact.Email">@contact.Email</a></td>
                    <td class="text-right">
                        <a href="@Url.Action("Edit", "Contact", new {Id = @contact.Id})" class="mini-btn">
                            <i class="fa fa-pencil"></i>
                        </a>
                        <a href="@Url.Action("Delete", "Contact", new {Id = @contact.Id})" class="mini-btn">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <div class="text-center">
            No Contacts for this Customer
        </div>
    }
</div>

InventoryManager/Views/Customer/__form_locations.cshtml
@model InventoryManager.ViewModel.CustomerData

<div class="section">
    <div class="section-header">
        <h3>Customer Location</h3>
        <div class="section-controls">
            <a href="@Url.Action("Add", "Location", new { CustomerId = Model.Id})">
                <span class="fa fa-plus"></span> Add Location
            </a>
        </div>
    </div>
    <div class="separator"></div>
</div>

<div class="row">
    @if (Model.Locations.Count > 0)
    {
        foreach (var location in Model.Locations)
        {
            <div class="col-sm-3">
                <div>
                    @location.Street<br/>
                    @if (location.Unit != null)
                    {
                        @location.Unit<br/>
                    }
                    @location.City, @location.State @location.Zip
                </div>
                @if (location.Phone != null)
                {
                    <div class="phone">
                        <span class="fa fa-phone"></span> @location.Phone
                    </div>
                }
                @if (location.Fax != null)
                {
                    <div class="fax">
                        <span class="fa fa-fax"></span> @location.Fax
                    </div>
                }

                <div class="controls">
                    <a href="@Url.Action("Edit", "Location", new {Id = location.Id})" class="mini-btn">
                        <span class="fa fa-pencil"></span>
                    </a>
                    <a href="@Url.Action("Delete", "Location", new {Id = location.Id})" class="mini-btn">
                        <span class="fa fa-trash"></span>
                    </a>
                </div>
            </div>
        }
    }
    else
    {
        <div class="text-center">
            No Locations for this Customer
        </div>
    }

</div>

InventoryManager/Views/Customer/_form_view.cshtml
@model InventoryManager.ViewModel.CustomerData

    <div class="row">
        @Html.LabelFor(h => h.Name, htmlAttributes: new { @class = "col-sm-2" })
        <div class="col-sm-10">
            <div class="form-group">
                <div class="data-box">@Model.Name</div>
            </div>
        </div>
    </div>
    <div class="row">
        @Html.LabelFor(h => h.Description, htmlAttributes: new { @class = "col-sm-2" })
        <div class="col-sm-10">
            <div class="form-group">
                <div class="data-box">@Model.Description</div>
            </div>
        </div>
    </div>