InventoryManager/Controllers/HardwareController.cs
using System;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using InventoryManager.Models;
using InventoryManager.ViewModel;
using Microsoft.AspNet.Identity;
using PagedList;

namespace InventoryManager.Controllers
{
    public class HardwareController : Controller
    {
        private InventoryContext db = new InventoryContext();
        
        // GET: Inventory
        public ActionResult Index(HardwareList viewModel)
        {
            viewModel.Hardwares = db.Hardwares
                .Include(h => h.Inventory)
                .Include(h => h.Inventory.Maker)
                .OrderBy(i => i.Inventory.Name)
                .ToPagedList(viewModel.Page, viewModel.PageSize);
            
            return View(viewModel);
        }

        public ActionResult Add()
        {
            var viewModel = new HardwareData();

            viewModel.HardwareTypes = db.HardwareTypes.Where(h => h.Status == true);
            viewModel.Vendors = db.Vendors.Where(v => v.Status == true);
            viewModel.Makers = db.Makers.Where(m => m.Status == true);
            viewModel.Owners = db.Owners.ToList();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(HardwareData h)
        {
            var hardware = new Hardware() { Inventory = new Inventory()};

            if(User.IsInRole(ApplicationUser.USER))
            {
                var userId = User.Identity.GetUserId();
                var employee = db.Employees
                    .Include(e => e.Owner)
                    .SingleOrDefault(e => e.User.Id == userId);
                if(employee == null ) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                h.OwnerId = employee.Owner.Id;
                h.Status = InventoryStatus.Pending;
            }

            if (!ModelState.IsValid)
            {
                PopulateHardware(hardware, h);
                h.HardwareTypes = db.HardwareTypes.Where(i => i.Status);
                h.Vendors = db.Vendors.Where(i => i.Status);
                h.Makers = db.Makers.Where(i => i.Status);
                h.Owners = db.Owners.ToList();

                return View(h);
            }

            UpdateHistory(hardware, h);
            MapHardware(hardware, h);
            hardware.Inventory.CreatedOn = DateTime.Now;

            db.Hardwares.Add(hardware);
            db.SaveChanges();

            TempData["AlertMessage"] = "Your Hardware is Saved.";
            return RedirectToAction("Show", new { Id = hardware.Id });
        }

        public void MapHardware(Hardware hardwareToUpdate, HardwareData data)
        {
            hardwareToUpdate.Inventory.Name = data.Name;
            hardwareToUpdate.Inventory.Description = data.Description;
            hardwareToUpdate.Inventory.ModelName = data.ModelName;
            hardwareToUpdate.Inventory.ModelNo = data.ModelNo;
            hardwareToUpdate.Inventory.ModelYear = data.ModelYear;
            hardwareToUpdate.Inventory.PurchasePrice = data.PurchasePrice;
            hardwareToUpdate.Inventory.PurchaseDate = data.PurchaseDate;
            hardwareToUpdate.Inventory.SerialNo = data.SerialNo;
            hardwareToUpdate.Inventory.MakerId = data.MakerId;
            hardwareToUpdate.Inventory.VendorId = data.VendorId;
            hardwareToUpdate.Inventory.OwnerId = data.OwnerId;
            hardwareToUpdate.Inventory.Status = data.Status == 0 ? InventoryStatus.Pending : data.Status;
            hardwareToUpdate.Inventory.ModifiedOn = DateTime.Now;
            
            hardwareToUpdate.HardwareTypeId = data.HardwareTypeId;
            hardwareToUpdate.WarrentyExpiration = data.WarrentyExpiration;
        }

        public void PopulateHardware(Hardware hardware, HardwareData hardwareToDisplay)
        {
            hardwareToDisplay.Name = hardware.Inventory.Name;
            hardwareToDisplay.Description = hardware.Inventory.Description;
            hardwareToDisplay.ModelName = hardware.Inventory.ModelName;
            hardwareToDisplay.ModelNo = hardware.Inventory.ModelNo;
            hardwareToDisplay.ModelYear = hardware.Inventory.ModelYear;
            hardwareToDisplay.PurchasePrice = hardware.Inventory.PurchasePrice;
            hardwareToDisplay.PurchaseDate = hardware.Inventory.PurchaseDate;
            hardwareToDisplay.SerialNo = hardware.Inventory.SerialNo;
            hardwareToDisplay.MakerId = hardware.Inventory.MakerId;
            hardwareToDisplay.VendorId = hardware.Inventory.VendorId;
            hardwareToDisplay.OwnerId = hardware.Inventory.OwnerId;
            hardwareToDisplay.Status = hardware.Inventory.Status;

            hardwareToDisplay.HardwareTypeId = hardware.HardwareTypeId;
            hardwareToDisplay.WarrentyExpiration = hardware.WarrentyExpiration;
        }

        public void UpdateHistory(Hardware hardware, HardwareData data)
        {
            if (data.Status != hardware.Inventory.Status
                || data.OwnerId != hardware.Inventory.OwnerId)
            {
                var history = new History()
                {
                    AssignedOn = DateTime.Now,
                    AssignedToId = data.OwnerId,
                    InventoryId = hardware.Inventory.Id,
                    StatusAssigned = data.Status,
                    AssignedById = User.Identity.GetUserId()
                };

                db.Histories.Add(history);
            }
        }
        public ActionResult Edit(int? Id)
        {
            if (Id == null ) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var hardware = db.Hardwares
                .Include(i => i.Inventory)
                .SingleOrDefault(i => i.Id == Id);

            if(hardware == null) return new HttpNotFoundResult();

            var userId = User.Identity.GetUserId();
            var employee = db.Employees
                .Include(e => e.Owner)
                .SingleOrDefault(i => i.User.Id == userId);
            if (employee == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (User.IsInRole(ApplicationUser.USER))
            {
                if (hardware.Inventory.Status != InventoryStatus.Pending || hardware.Inventory.OwnerId != employee.Owner.Id)
                {
                    return new HttpUnauthorizedResult();
                }
            }
            
            var viewModel = new HardwareData();
            
            PopulateHardware(hardware, viewModel);
            viewModel.HardwareTypes = db.HardwareTypes.Where(h => h.Status == true);
            viewModel.Vendors = db.Vendors.Where(v => v.Status == true);
            viewModel.Makers = db.Makers.Where(m => m.Status == true);
            viewModel.Owners = db.Owners.ToList();

            viewModel.ReferrerUrl = Request.UrlReferrer?.AbsoluteUri;
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HardwareData h)
        {
            var hardware = db.Hardwares
                .Include(i => i.Inventory)
                .SingleOrDefault(i => i.Id == h.Id);
            if (hardware == null) return new HttpNotFoundResult();

            var userId = User.Identity.GetUserId();
            var employee = db.Employees
                .Include(e => e.Owner)
                .SingleOrDefault(i => i.User.Id == userId);

            if (employee == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (User.IsInRole(ApplicationUser.USER))
            {
                if (hardware.Inventory.Status != InventoryStatus.Pending || hardware.Inventory.OwnerId != employee.Owner.Id)
                {
                    return new HttpUnauthorizedResult();
                }

                h.Status = InventoryStatus.Pending;
                h.OwnerId = employee.Owner.Id;
            }

            if (!ModelState.IsValid)
            {
                PopulateHardware(hardware, h);
                h.HardwareTypes = db.HardwareTypes.Where(i => i.Status);
                h.Vendors = db.Vendors.Where(i => i.Status);
                h.Makers = db.Makers.Where(i => i.Status);
                h.Owners = db.Owners.ToList();

                return View(h);
            }

            UpdateHistory(hardware, h);
            MapHardware(hardware, h);
            db.SaveChanges();

            TempData["AlertMessage"] = "Your Hardware is Saved.";
            return RedirectToAction("Show", new { Id = hardware.Id });
        }

        public ActionResult Show(int? Id)
        {
            if (Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var viewModel = new HardwareView();

            var hardware = db.Hardwares
                .Include(h => h.Inventory)
                .Include(h => h.Inventory.Maker)
                .Include(h => h.Inventory.Vendor)
                .Include(h => h.HardwareType)
                .Include(h => h.Inventory.Owner)
                .Include(h => h.Inventory.Documents)
                .SingleOrDefault(h => h.Id == Id);

            var userId = User.Identity.GetUserId();
            var employee = db.Employees
                .Include(e => e.Owner)
                .SingleOrDefault(i => i.User.Id == userId);

            if (User.IsInRole(ApplicationUser.USER) && hardware.Inventory.OwnerId != employee.Owner.Id)
            {
                return new HttpUnauthorizedResult();
            }

            if (hardware == null) return new HttpNotFoundResult();

            viewModel.Hardware = hardware;

            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

InventoryManager/Controllers/HardwareTypeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventoryManager.Models;
using InventoryManager.ViewModel;
using PagedList;

namespace InventoryManager.Controllers
{
    [Authorize(Roles = "InventoryManager, InventoryCustomerManager, InventoryAdmin")]
    public class HardwareTypeController : Controller
    {
        private InventoryContext db = new InventoryContext();
        // GET: HardwareType
        public ActionResult Index(HardwareTypeTableView viewModel)
        {
            viewModel.HardwareTypeTables = db.HardwareTypes
                .Select(h => new HardwareTypeTable()
                {
                    HardwareType = h,
                    Count = h.Hardwares.Count
                })
                .OrderBy(h => h.HardwareType.Name)
                .ToPagedList(viewModel.Page, viewModel.PageSize);

            return View(viewModel);
        }

        public ActionResult ListInventories(int? Id, HardwareTypeHardwareList viewModel)
        {
            if (Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var hardwareType = db.HardwareTypes.Find(Id);

            if(hardwareType == null) return new HttpNotFoundResult();

            viewModel.Hardwares = db.Hardwares.Where(h => h.HardwareTypeId == hardwareType.Id)
                    .Include(i => i.Inventory.Owner)
                    .OrderBy(h => h.Inventory.Name)
                    .ToPagedList(viewModel.Page, viewModel.PageSize);

            viewModel.HardwareType = hardwareType;

            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

InventoryManager/Views/HardwareType/Index.cshtml
@using PagedList.Mvc
@model InventoryManager.ViewModel.HardwareTypeTableView
@{
    ViewBag.Title = "Hardware Types";
    Layout = "../Shared/_FormLayout.cshtml";
}

@section PageHead{
    <h2>@ViewBag.Title</h2>
}

@section MenuControls {
}

<div class="list">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th class="col-sm-8">Name</th>
            <th class="col-sm-2 text-center">Hardware Count</th>
            <th class="col-sm-2 text-right">Action</th>
        </tr>
        </thead>

        @foreach (var hardwareType in Model.HardwareTypeTables)
        {
            <tr class="">
                <td>@hardwareType.HardwareType.Name</td>
                <td class="text-center">@hardwareType.Count</td>
                <td class="text-right">
                    <a href="@Url.Action("ListInventories", "HardwareType", new {Id = hardwareType.HardwareType.Id})" class="mini-btn">
                        <i class="fa fa-list"></i> List
                    </a>
                </td>
            </tr>
        }
    </table>
    
    @if (Model.HardwareTypeTables.PageSize < Model.HardwareTypeTables.TotalItemCount)
    {
    <div class="text-center">
        @Html.PagedListPager(Model.HardwareTypeTables, page => Url.Action("Index",
            new {page}))
    </div>
    }
</div>

InventoryManager/Views/HardwareType/ListInventories.cshtml
@using PagedList.Mvc
@model InventoryManager.ViewModel.HardwareTypeHardwareList
@{
    ViewBag.Title = Model.HardwareType.Name;

    Layout = "../Shared/_FormLayout.cshtml";
}

@section PageHead{
    <h2>Hardware List: @ViewBag.Title

    </h2>
    <div class="info">
        <span class="info-type">Total Inventories:</span>
        @Model.Hardwares.TotalItemCount
    </div>
}

@section MenuControls {
    <ul>
        <li>
            <a href="@Url.Action("Index", "HardwareType")"><i class="fa fa-undo"></i> Back to Hardware Types</a>
        </li>
    </ul>
}

<div class="list">
    @if (Model.Hardwares.Count > 0)
    {
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th width="25%">Name</th>
                <th class="col-sm-2 text-center">Status</th>
                <th class="col-sm-2">Assigned to</th>
                <th class="col-sm-1 text-right">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var hardware in Model.Hardwares)
            {
                <tr>
                    <td>
                        @hardware.Inventory.Name
                    </td>
                    <td class="text-center">
                        <span class="label label-@hardware.Inventory.Status">@hardware.Inventory.Status</span>
                    </td>
                    <td>
                        <a href="@Url.Action("Show", "Customer", new {Id = @hardware.Inventory.Owner.Id})">
                            <i class="fa fa-user"></i> @hardware.Inventory.Owner.Name
                        </a>
                    </td>
                    <td class="text-right">
                        <a href="@Url.Action("Show", "Hardware", new {Id = @hardware.Id})" class="mini-btn">
                            <i class="fa fa-eye"></i>
                        </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>

        if (Model.Hardwares.PageSize < Model.Hardwares.TotalItemCount)
         {
             <div class="text-center">
                 @Html.PagedListPager(Model.Hardwares, page => Url.Action("ListInventories", "HardwareType",
                     new {page}))
             </div>
         }
    }
    else
    {
        <div class="text-center">
            No Inventories under @Model.HardwareType.Name
        </div>
    }
</div>