InventoryManager/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventoryManager.Models;
using InventoryManager.ViewModel;
using PagedList;

namespace InventoryManager.Controllers
{
    public class VendorController : Controller
    {
        private InventoryContext db = new InventoryContext();
        // GET: HardwareType
        public ActionResult Index(VendorTableView viewModel)
        {

            viewModel.VendorTables = db.Vendors
                .Select(h => new VendorTable()
                {
                    Vendor = h,
                    Count = h.Inventories.Count
                })
                .OrderBy(v => v.Vendor.Name)
                .ToPagedList(viewModel.Page, viewModel.PageSize);
            
            return View(viewModel);
        }

        public ActionResult ListInventories(int? Id, VendorInventoryList viewModel)
        {
            if (Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var vendor = db.Vendors.Find(Id);

            if(vendor == null) return new HttpNotFoundResult();

            viewModel.Vendor = vendor;

            viewModel.Inventories = db.Inventories.Where(h => h.VendorId == vendor.Id)
                .Include(i => i.Owner)
                .OrderBy(v => v.Name)
                .ToPagedList(viewModel.Page, viewModel.PageSize);

            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

InventoryManager/Views/Vendor/Index.cshtml
@using PagedList.Mvc
@model InventoryManager.ViewModel.VendorTableView
@{
    ViewBag.Title = "Vendors";
    Layout = "../Shared/_FormLayout.cshtml";
}

@section PageHead{
    <h2>@ViewBag.Title</h2>
}

@section MenuControls {
}

<div class="list">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th class="col-sm-8">Name</th>
            <th class="col-sm-2 text-center">Inventory Count</th>
            <th class="col-sm-2 text-right">Action</th>
        </tr>
        </thead>

        @foreach (var vendorTable in Model.VendorTables)
        {
            <tr class="">
                <td>@vendorTable.Vendor.Name</td>
                <td class="text-center">@vendorTable.Count</td>
                <td class="text-right">
                    <a href="@Url.Action("ListInventories", "Vendor", new {Id = vendorTable.Vendor.Id})" class="mini-btn">
                        <i class="fa fa-list"></i> List
                    </a>
                </td>
            </tr>
        }
    </table>
    
    @if (Model.VendorTables.PageSize < Model.VendorTables.TotalItemCount)
    {
        <div class="text-center">
            @Html.PagedListPager(Model.VendorTables, page => Url.Action("Index",
                new {page}))
        </div>
    }
</div>

InventoryManager/Views/Vendor/ListInventories.cshtml
@using PagedList.Mvc
@model InventoryManager.ViewModel.VendorInventoryList
@{
    ViewBag.Title = Model.Vendor.Name;

    Layout = "../Shared/_FormLayout.cshtml";
}

@section PageHead{
    <h2>Hardware List: @ViewBag.Title

    </h2>
    <div class="info">
        <span class="info-type">Total Inventories:</span>
        @Model.Inventories.TotalItemCount
    </div>
}

@section MenuControls {
    <ul>
        <li>
            <a href="@Url.Action("Index", "Vendor")"><i class="fa fa-undo"></i> Back to Vendors</a>
        </li>
    </ul>
}

<div class="list">
    @if (Model.Inventories.Count > 0)
    {
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th width="25%">Name</th>
                <th class="col-sm-2 text-center">Status</th>
                <th class="col-sm-2">Assigned to</th>
                <th class="col-sm-1 text-right">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var inventory in Model.Inventories)
            {
                <tr>
                    <td>
                        @inventory.Name
                    </td>
                    <td class="text-center">
                        <span class="label label-@inventory.Status">@inventory.Status</span>
                    </td>
                    <td>
                        <a href="@Url.Action("Show", "Customer", new {Id = @inventory.Owner.Id})">
                            <i class="fa fa-user"></i> @inventory.Owner.Name
                        </a>
                    </td>
                    <td class="text-right">
                        <a href="@Url.Action("Show", "Inventory", new {Id = @inventory.Id})" class="mini-btn">
                            <i class="fa fa-eye"></i>
                        </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        
        if (Model.Inventories.PageSize < Model.Inventories.TotalItemCount)
        {
            <div class="text-center">
                @Html.PagedListPager(Model.Inventories, page => Url.Action("ListInventories", "Vendor",
                    new {Id = Model.Vendor.Id, page}))
            </div>
        }
    }
    else
    {
        <div class="text-center">
            No Inventories under @Model.Vendor.Name
        </div>
    }
</div>